### ISSUE TITLE
See if we can make tasks cacheable

### ISSUE THREAD

**Issue by joshafeinberg** [dropbox/AffectedModuleDetector#150]
This will be a tracking ticket. In 0.1.6 we will be marking those tasks as not cacheable but would like to investigate if it's possible to somehow do this. Our current problem is this stack trace

```
Caused by: org.gradle.api.UnknownDomainObjectException: Extension with name 'AffectedModuleDetectorPlugin' does not exist. Currently registered extension names: [ext]
        at org.gradle.internal.extensibility.ExtensionsStorage.unknownExtensionException(ExtensionsStorage.java:144)
        at org.gradle.internal.extensibility.ExtensionsStorage.getByName(ExtensionsStorage.java:123)
        at org.gradle.internal.extensibility.DefaultConvention.getByName(DefaultConvention.java:174)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetector$Companion.getInstance(AffectedModuleDetector.kt:195)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetector$Companion.getOrThrow(AffectedModuleDetector.kt:200)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetector$Companion.configureTaskGuard$lambda-3(AffectedModuleDetector.kt:233)
        at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:50)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:44)
        ... 24 more

```

As noted in this [slack message](https://gradle-community.slack.com/archives/C013WEPGQF9/p1657139676627849) on the gradle slack, the `apply` method is not called on plugins which cached so the call in our `onlyIf` block to check if a project is enabled and affected no longer works. If we could move that check into the task possibly rather then the plugin maybe this is doable

**Comment by bddckr** [comment]
It looks like the AndroidX implementation had some [recent changes](https://github.com/androidx/androidx/commits/androidx-main/buildSrc/private/src/main/kotlin/androidx/build/dependencyTracker) to fix Gradle configuration cache issues, along with some issues for Gradle's (upcoming) project isolation feature:
* https://github.com/androidx/androidx/commit/60aa3e56a4b1dfe8dc45dcb744a33289247d89c9
* https://github.com/androidx/androidx/commit/85add7063b366b55e114d824c53604d5d37dbd8d
* https://github.com/androidx/androidx/commit/f2f81c51d8a1c9c76b5e982b67e12e025eb63309

Perhaps that can help.
