### ISSUE TITLE
runAffectedUnitTests -Paffected_module_detector.enable failed for onlyIf

### ISSUE THREAD

**Issue by grzegorzbielanski** [dropbox/AffectedModuleDetector#67]
When run `./gradlew runAffectedUnitTests -Paffected_module_detector.enable` it fails in my project with error:

```
* What went wrong:
Could not evaluate onlyIf predicate for task ':somemodule:testDebugUnitTest'.
> Nonzero exit value running git command.

```

Stacktrace
```
* Exception is:
org.gradle.api.GradleException: Could not evaluate onlyIf predicate for task ':api:somemodule:testDebugUnitTest'.
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:200)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:195)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:75)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$3.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:153)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:68)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:62)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.lambda$call$2(DefaultBuildOperationExecutor.java:79)
        at org.gradle.internal.operations.UnmanagedBuildOperationWrapper.callWithUnmanagedSupport(UnmanagedBuildOperationWrapper.java:54)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:79)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:408)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:395)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:388)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:374)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:127)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:191)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:182)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.IllegalStateException: Nonzero exit value running git command.
        at com.dropbox.affectedmoduledetector.GitClientImpl$RealCommandRunner.execute(GitClient.kt:162)
        at com.dropbox.affectedmoduledetector.GitClientImpl$RealCommandRunner.executeAndParse(GitClient.kt:166)
        at com.dropbox.affectedmoduledetector.GitClientImpl$RealCommandRunner.executeAndParseFirst(GitClient.kt:176)
        at com.dropbox.affectedmoduledetector.commitshaproviders.ForkCommit.get(ForkCommit.kt:8)
        at com.dropbox.affectedmoduledetector.GitClientImpl.findChangedFiles(GitClient.kt:80)
        at com.dropbox.affectedmoduledetector.GitClient$DefaultImpls.findChangedFiles$default(GitClient.kt:31)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl.findChangedProjects(AffectedModuleDetector.kt:403)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl.access$findChangedProjects(AffectedModuleDetector.kt:314)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl$changedProjects$2.invoke(AffectedModuleDetector.kt:354)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl$changedProjects$2.invoke(AffectedModuleDetector.kt:314)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl.getChangedProjects(AffectedModuleDetector.kt)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl.findAffectedProjects(AffectedModuleDetector.kt:462)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl.access$findAffectedProjects(AffectedModuleDetector.kt:314)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl$affectedProjects$2.invoke(AffectedModuleDetector.kt:350)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl$affectedProjects$2.invoke(AffectedModuleDetector.kt:314)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl.getAffectedProjects(AffectedModuleDetector.kt)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorImpl.shouldInclude(AffectedModuleDetector.kt:366)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetector$Companion.isProjectAffected(AffectedModuleDetector.kt:254)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorPlugin$withPlugin$1$$special$$inlined$let$lambda$1$1.isSatisfiedBy(AffectedModuleDetectorPlugin.kt:98)
        at com.dropbox.affectedmoduledetector.AffectedModuleDetectorPlugin$withPlugin$1$$special$$inlined$let$lambda$1$1.isSatisfiedBy(AffectedModuleDetectorPlugin.kt:36)
        at org.gradle.api.specs.AndSpec.isSatisfiedBy(AndSpec.java:50)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:44)
        ... 30 more

```

**Comment by grzegorzbielanski** [comment]
Both commands below works fine:
```
./gradlew runAffectedUnitTests -Paffected_module_detector.changedProjects
./gradlew runAffectedUnitTests
```

**Comment by grzegorzbielanski** [comment]
version 0.1.2
